import * as vscode from 'vscode';
import { Client, Evidence, Result, Source } from './protocol';

type Preview={key:string;result:Result;evidence:Evidence;page?:number;generation:number};
const scheme='findrail-evidence';
class Provider implements vscode.TextDocumentContentProvider {
 private emitter=new vscode.EventEmitter<vscode.Uri>(); readonly onDidChange=this.emitter.event;
 private entries=new Map<string,Preview>();
 put(p:Preview){this.entries.delete(p.key);this.entries.set(p.key,p);while(this.entries.size>10||this.bytes()>4*1024*1024){const first=this.entries.keys().next().value;if(first) this.entries.delete(first);else break}}
 get(key:string){return this.entries.get(key)}
 remove(key:string){this.entries.delete(key)}
 clear(){this.entries.clear()}
 dispose(){this.clear();this.emitter.dispose()}
 provideTextDocumentContent(uri:vscode.Uri){const p=this.entries.get(uri.path.slice(1));return p?evidenceText(p.evidence,p.page):'This Findrail evidence preview is no longer available. Refresh it from a current result.'}
 private bytes(){return [...this.entries.values()].reduce((n,p)=>n+Buffer.byteLength(p.evidence.text,'utf8'),0)}
}
let client:Client|undefined, selected:Source|undefined, mode:'literal'|'advanced'='literal', filters={format:'',path_prefix:'',title_contains:''}, active:Preview|undefined, generation=0, controller:AbortController|undefined;
let ctx:vscode.ExtensionContext, provider:Provider;
function userConfig(){return vscode.workspace.getConfiguration('findrail',null)}
function setting<T>(key:string,fallback:T):T{return userConfig().inspect<T>(key)?.globalValue??fallback}
function makeClient(){const raw=setting('timeoutSeconds',5);const timeout=Number.isFinite(raw)?Math.max(1,Math.min(30,raw)):5;return new Client(setting('endpoint','http://127.0.0.1:7766'),timeout)}
function searchLimit(){const raw=setting('searchLimit',20);return Number.isFinite(raw)?Math.max(1,Math.min(100,Math.trunc(raw))):20}
function setActive(p?:Preview){active=p;void vscode.commands.executeCommand('setContext','findrail.evidenceActive',!!p);void vscode.commands.executeCommand('setContext','findrail.evidencePdf',!!p&&p.evidence.media_type==='application/pdf'&&!!p.evidence.page_count)}
function cancel(){controller?.abort();controller=undefined;generation++}
function safeLabel(s:string){return s.replace(/[\u0000-\u001f\u007f-\u009f\u2028\u2029\u202a-\u202e\u2066-\u2069]/gu,' ').slice(0,180)}
function evidenceText(e:Evidence,page?:number){return [safeLabel(e.title),`Source: ${safeLabel(e.source_name)} (${safeLabel(e.source_id)}; ${safeLabel(selected?.kind??'indexed')})`,`Indexed path: ${safeLabel(e.path)}`,`Original location: ${safeLabel(e.uri)}`,`Index snapshot: ${safeLabel(selected?.last_indexed_at??'unknown')}`,`Document modified: ${safeLabel(e.modified_at)}`,...(page!==undefined?[`PDF page: ${page}`]:[]),'',e.text,...(e.truncated?['','[Preview truncated; only bounded indexed text is shown.]']:[])].join('\n')}
async function connected(signal?:AbortSignal){if(!client){client=makeClient();await client.connect(signal)}return client}
async function listSources(signal?:AbortSignal){const c=await connected(signal);return c.sources(signal)}
async function chooseSource(){cancel();const gen=generation;controller=new AbortController();const sources=await listSources(controller.signal);if(gen!==generation)return;if(!sources.length){selected=undefined;throw Error('No indexed sources are available.')}const pick=await vscode.window.showQuickPick(sources.map(s=>({label:safeLabel(`${s.name} · ${s.kind==='archive'?'frozen archive':s.kind}`),description:`${s.documents} documents · ${s.last_indexed_at}`,detail:safeLabel(s.root),source:s})),{placeHolder:'Choose one source; searches are always limited to this source',matchOnDetail:false});if(!pick||gen!==generation){cancel();return}cancel();selected=pick.source;provider.clear();setActive(undefined)}
async function refreshSources(){cancel();const gen=generation;controller=new AbortController();const old=selected?.id;const sources=await listSources(controller.signal);if(gen!==generation)return;if(old&&!sources.some(s=>s.id===old)){selected=undefined;setActive(undefined);provider.clear();vscode.window.showWarningMessage('The selected Findrail source was removed. Choose a source before searching.')}else if(selected)selected=sources.find(s=>s.id===selected!.id)}
function activeContext(){const fs=Object.entries(filters).filter(([,v])=>v).map(([k,v])=>`${k}=${safeLabel(v)}`).join(', ')||'none';return `${safeLabel(selected!.name)} · ${mode} · filters: ${fs}`}
async function showEvidence(result:Result,page?:number){cancel();const gen=generation;controller=new AbortController();const c=await connected(controller.signal);const e=await c.evidence(result,page,controller.signal);if(gen!==generation||!selected||selected.id!==result.source_id)return;const citationModule=await import('./citation.mjs');e.uri=citationModule.sourceURI(result.uri);const key=`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;const preview:Preview={key,result,evidence:e,page,generation:gen};provider.put(preview);if(!provider.get(key))throw Error('preview_exceeds_cache');setActive(preview);const uri=vscode.Uri.from({scheme,path:`/${key}`,query:'',fragment:e.media_type==='application/pdf'&&e.page?`page=${e.page}`:''});const doc=await vscode.workspace.openTextDocument(uri);await vscode.window.showTextDocument(doc,{preview:true});}
async function search(prefill?:string){if(!selected){await chooseSource();if(!selected)return}cancel();const gen=generation;const q=await vscode.window.showInputBox({title:'Findrail: Search',prompt:activeContext(),ignoreFocusOut:true,value:prefill});if(q===undefined)return;if(!q.trim()){vscode.window.showWarningMessage('Enter a search query.');return}if(Array.from(q).length>256){vscode.window.showErrorMessage('Findrail queries are limited to 256 Unicode code points. Edit the query and try again.');return search(q)}controller=new AbortController();try{const response=await (await connected(controller.signal)).search(q,selected.id,mode,filters,searchLimit(),controller.signal);if(gen!==generation||!selected)return;if(!response.results.length){vscode.window.showInformationMessage(`No results in ${safeLabel(selected.name)} (${response.total} total matches).`);return}const picks=response.results.map(r=>({label:safeLabel(r.title),description:safeLabel(`${r.path} · ${r.source_name}${r.page?` · PDF page ${r.page}`:''} · ${r.media_type}`),detail:safeLabel(r.snippet),result:r}));const chosen=await vscode.window.showQuickPick(picks,{title:`${activeContext()} · ${response.results.length} returned of ${response.total}${response.total>response.results.length?' (limited)':''}`,matchOnDescription:true,matchOnDetail:true});if(!chosen||gen!==generation)return;await showEvidence(chosen.result,chosen.result.media_type==='application/pdf'?chosen.result.page??0:undefined)}catch(e:any){if(e?.message==='canceled')return;if(e?.message?.startsWith('query_validation|')){const [,code,position,message]=e.message.split('|');vscode.window.showErrorMessage(`Findrail query ${code}${position?` at code-point ${position}`:''}: ${message}`);return search(q)}if(gen===generation)vscode.window.showErrorMessage(e?.message==='compatible_build_required'?'A compatible source build is required (client API v1).':'Findrail request failed. Check the loopback server and try again.')}}
function requirePreview(){const editor=vscode.window.activeTextEditor;const p=active;if(!p||!provider.get(p.key)||editor?.document.uri.scheme!==scheme||editor.document.uri.path!==`/${p.key}`){vscode.window.showWarningMessage('No current Findrail evidence preview is active.');return}return p}
export async function activate(context:vscode.ExtensionContext){ctx=context;provider=new Provider();context.subscriptions.push(vscode.workspace.registerTextDocumentContentProvider(scheme,provider));
 const cmd=(id:string,fn:(...a:any[])=>any)=>context.subscriptions.push(vscode.commands.registerCommand(`findrail.${id}`,fn));
 cmd('connect',async()=>{cancel();const gen=generation;controller=new AbortController();try{client=makeClient();await client.connect(controller.signal);const s=await client.sources(controller.signal);if(gen===generation)vscode.window.showInformationMessage(`Connected to Findrail. ${s.length} sources available.`)}catch(e:any){if(gen!==generation||e.message==='canceled')return;client=undefined;if(e.message==='compatible_build_required')vscode.window.showErrorMessage('A compatible source build is required (client API v1).');else vscode.window.showErrorMessage('Could not connect to the configured loopback Findrail server.')}});
 cmd('chooseSource',chooseSource);cmd('search',()=>search());cmd('searchSelection',async()=>{const selection=vscode.window.activeTextEditor?.document.getText(vscode.window.activeTextEditor.selection);await search(selection||undefined)});
 cmd('setMode',async()=>{cancel();const v=await vscode.window.showQuickPick([{label:'Literal',description:'Default; punctuation and operators have no special meaning',value:'literal'},{label:'Advanced',description:'Explicit query grammar',value:'advanced'}],{placeHolder:'Search mode'});if(v){mode=v.value as any;vscode.window.showInformationMessage(`Findrail mode: ${mode}`)}});
 cmd('setFilters',async()=>{cancel();const action=await vscode.window.showQuickPick([{label:'Set filters'},{label:'Reset filters'}],{placeHolder:'Filters apply on the server before result limits'});if(!action)return;if(action.label==='Reset filters'){filters={format:'',path_prefix:'',title_contains:''};return}const format=await vscode.window.showQuickPick(['all','text','pdf','docx'],{placeHolder:`Format filter (current: ${filters.format||'all'})`});if(format===undefined)return;const path=await vscode.window.showInputBox({prompt:'Relative path prefix; leave empty for none',value:filters.path_prefix});if(path===undefined)return;const title=await vscode.window.showInputBox({prompt:'Title contains (case-sensitive); leave empty for none',value:filters.title_contains});if(title===undefined)return;filters={format:format==='all'?'':format,path_prefix:path,title_contains:title};});
 cmd('refreshSources',refreshSources);cmd('disconnect',()=>{cancel();client=undefined;selected=undefined;provider.clear();setActive(undefined)});
 cmd('refreshEvidence',async()=>{const p=requirePreview();if(p)await showEvidence(p.result,p.page)});
 cmd('nextPage',async()=>{const p=requirePreview();if(!p||p.evidence.media_type!=='application/pdf'||!p.evidence.page_count)return;const page=(p.page??0)+1;if(page>p.evidence.page_count){vscode.window.showInformationMessage('Already at the last PDF page.');return}await showEvidence(p.result,page)});
 cmd('previousPage',async()=>{const p=requirePreview();if(!p||p.evidence.media_type!=='application/pdf'||!p.evidence.page_count)return;const page=(p.page??0)-1;if(page<0){vscode.window.showInformationMessage('Already at the title-only PDF evidence.');return}await showEvidence(p.result,page)});
 cmd('copyLocation',async()=>{const p=requirePreview();if(!p)return;await vscode.env.clipboard.writeText(p.evidence.uri);vscode.window.showInformationMessage('Findrail location copied.')});
 cmd('copyCitation',async()=>{const p=requirePreview();if(!p)return;const editor=vscode.window.activeTextEditor;let excerpt:string|undefined;if(editor?.document.uri.scheme===scheme&&editor.selection&&!editor.selection.isEmpty){excerpt=editor.document.getText(editor.selection);if(!excerpt||!p.evidence.text.includes(excerpt)){vscode.window.showWarningMessage('Selection is not an exact non-empty excerpt of this evidence.');return}}
  const formatter=await import('./citation.mjs');const citation=formatter.formatCitation({...p.evidence,text:p.evidence.text,media_type:p.evidence.media_type,page:p.evidence.page,uri:p.evidence.uri},excerpt===undefined?{}:{excerpt});await vscode.env.clipboard.writeText(citation);vscode.window.showInformationMessage('Findrail Markdown citation copied.')});
 context.subscriptions.push(provider,vscode.workspace.onDidChangeConfiguration(e=>{if(e.affectsConfiguration('findrail.endpoint')){cancel();client=undefined;selected=undefined;provider.clear();setActive(undefined)}}));
 context.subscriptions.push(vscode.window.onDidChangeActiveTextEditor(editor=>{const key=editor?.document.uri.scheme===scheme?editor.document.uri.path.slice(1):'';setActive(key?provider.get(key):undefined)}));
 context.subscriptions.push(vscode.workspace.onDidCloseTextDocument(document=>{if(document.uri.scheme!==scheme)return;const key=document.uri.path.slice(1);provider.remove(key);if(active?.key===key){cancel();setActive(undefined)}}));
}
export function deactivate(){cancel();client=undefined;selected=undefined;provider?.dispose();setActive(undefined)}
