import http from 'node:http';
import dns from 'node:dns';
import { isIP } from 'node:net';

export type Source = {id:string;kind:string;name:string;root:string;documents:number;last_indexed_at:string};
export type Result = {id:string;title:string;uri:string;path:string;source_id:string;source_name:string;source_kind:string;snippet:string;score:number;media_type:string;page?:number;page_count?:number};
export type Evidence = {id:string;title:string;uri:string;path:string;source_id:string;source_name:string;source_kind?:string;media_type:string;page?:number;page_count?:number;content_hash:string;modified_at:string;text:string;truncated:boolean};
const text = (v:unknown,max=65536):v is string => typeof v==='string' && Buffer.byteLength(v,'utf8')<=max && !/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(v) && !/(?:[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF])/u.test(v);
const id = (v:unknown):v is string => typeof v==='string' && /^[A-Za-z0-9_-]{1,128}$/.test(v);
export function endpoint(raw:unknown):URL {
 if(typeof raw!=='string') throw Error('endpoint_invalid');
 let u:URL; try{u=new URL(raw)}catch{throw Error('endpoint_invalid')}
 if(u.protocol!=='http:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash||!['127.0.0.1','localhost','[::1]'].includes(u.hostname)) throw Error('endpoint_invalid');
 const port=u.port?Number(u.port):80; if(!Number.isInteger(port)||port<1||port>65535) throw Error('endpoint_invalid');
 return u;
}
export class Client {
 private active=0; private readonly host:URL; constructor(raw:string,private timeout:number){this.host=endpoint(raw)}
 private async get(path:string,max:number,signal?:AbortSignal,deadlineAt?:number):Promise<any>{
  if(!/^\/(?:healthz|api\/v1\/(?:capabilities|sources|search(?:\?[^#]*)?|documents\/[A-Za-z0-9_-]{1,128}(?:\?page=[0-9]{1,6})?))$/.test(path)) throw Error('route_denied');
  if(this.active>=4) throw Error('busy'); this.active++;
  try {return await new Promise((resolve,reject)=>{
   const remaining=deadlineAt===undefined?this.timeout*1000:Math.min(this.timeout*1000,deadlineAt-Date.now());if(remaining<=0)return reject(Error('deadline'));const timer=setTimeout(()=>req.destroy(Error('deadline')),remaining); const abort=()=>req.destroy(Error('canceled'));
   const opts: http.RequestOptions={protocol:'http:',hostname:this.host.hostname.replace(/^\[|\]$/g,''),port:this.host.port||80,path,method:'GET',headers:{'Accept':'application/json','Accept-Encoding':'identity'},agent:false,lookup:(hostname,options,cb)=>{
    if(hostname==='localhost'){dns.lookup(hostname,{all:true,verbatim:true},(err,addresses)=>{if(err)return cb(err, '127.0.0.1',4);const found=addresses.find(a=>a.address==='127.0.0.1'||a.address==='::1');if(!found)return cb(Error('non_loopback_dns'),'',0);cb(null,found.address,found.family)})}
    else cb(null,hostname, isIP(hostname));
   }};
   const req=http.request(opts,res=>{const contentType=String(res.headers['content-type']??'').split(';',1)[0].trim().toLowerCase();if(res.headers.location||contentType!=='application/json'||res.headers['content-encoding']&&res.headers['content-encoding']!=='identity'){res.destroy();clearTimeout(timer);return reject(Error('http_rejected'))}if(res.statusCode!==200){if(res.statusCode!==400||!path.startsWith('/api/v1/search?')){res.destroy();clearTimeout(timer);return reject(Error('http_rejected'))}const parts:Buffer[]=[];let n=0;let failed=false;res.on('data',(c:Buffer)=>{n+=c.length;if(n>8192){failed=true;res.destroy();clearTimeout(timer);reject(Error('error_body_oversize'));return}parts.push(c)});res.on('end',()=>{if(failed)return;clearTimeout(timer);try{const e=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Buffer.concat(parts)));if(!text(e?.error,512)||!['syntax','missing_positive_term','query_too_large','invalid_mode','invalid_filter'].includes(e.code)||e.position!==undefined&&(!Number.isSafeInteger(e.position)||e.position<0))throw Error();reject(Error(`query_validation|${e.code}|${e.position??''}|${e.error.replace(/[\u0000-\u001f\u007f]/g,' ')}`))}catch{reject(Error('query_validation_invalid'))}});res.on('error',()=>{if(failed)return;clearTimeout(timer);reject(Error('transport'))});return}if(res.statusCode!==200){res.destroy();clearTimeout(timer);return reject(Error('http_rejected'))}let chunks:Buffer[]=[];let size=0;let failed=false;res.on('data',(c:Buffer)=>{size+=c.length;if(size>max){failed=true;res.destroy();clearTimeout(timer);req.destroy();reject(Error('oversize'));return}chunks.push(c)});res.on('end',()=>{if(failed)return;clearTimeout(timer);try{const body=Buffer.concat(chunks);const value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(body));resolve(value)}catch{reject(Error('invalid_json'))}});res.on('error',()=>{if(failed)return;clearTimeout(timer);reject(Error('transport'))})});
   const done=()=>{clearTimeout(timer);signal?.removeEventListener('abort',abort)};req.on('close',done);req.on('error',e=>{clearTimeout(timer);reject(e.message==='canceled'?Error('canceled'):e.message==='deadline'?Error('deadline'):Error('transport'))}); if(signal?.aborted){abort();return}signal?.addEventListener('abort',abort,{once:true});req.end();
  })} finally {this.active--}
 }
 async connect(signal?:AbortSignal){const deadline=Date.now()+this.timeout*1000;const h=await this.get('/healthz',65536,signal,deadline);if(h?.status!=='ok')throw Error('health_invalid');const c=await this.get('/api/v1/capabilities',65536,signal,deadline);if(c?.client_api_version!==1||!Array.isArray(c.search_modes)||!c.search_modes.includes('literal')||!c.search_modes.includes('advanced')||!Array.isArray(c.search_filters)||!['source','format','path_prefix','title_contains'].every(x=>c.search_filters.includes(x))||c.pdf_title_only_evidence!==true)throw Error('compatible_build_required');return c}
 async sources(signal?:AbortSignal):Promise<Source[]>{const v=await this.get('/api/v1/sources',1<<20,signal);if(!Array.isArray(v?.sources)||v.sources.length>10000)throw Error('sources_invalid');return v.sources.map((s:any)=>{if(!id(s.id)||!text(s.name,512)||!['filesystem','github','archive'].includes(s.kind)||!text(s.root,4096)||!Number.isSafeInteger(s.documents)||s.documents<0||!text(s.last_indexed_at,80)||!Number.isFinite(Date.parse(s.last_indexed_at)))throw Error('source_invalid');return {id:s.id,kind:s.kind,name:s.name,root:s.root,documents:s.documents,last_indexed_at:s.last_indexed_at}})}
 async search(q:string,source:string,mode:string,filters:any,limit:number,signal?:AbortSignal):Promise<{total:number;results:Result[]}>{const p=new URLSearchParams({q,source,mode,limit:String(limit)});for(const k of ['format','path_prefix','title_contains'])if(filters[k])p.set(k,filters[k]);const v=await this.get('/api/v1/search?'+p,2<<20,signal);if(!Number.isSafeInteger(v?.total)||v.total<0||!Array.isArray(v.results)||v.results.length>limit||v.results.length>v.total)throw Error('search_invalid');const results=v.results.map((r:any)=>{if(!id(r.id)||r.source_id!==source||!text(r.title,4096)||!text(r.path,2048)||!text(r.uri,8192)||!text(r.source_name,512)||!['filesystem','github','archive'].includes(r.source_kind)||!text(r.snippet,8192)||typeof r.score!=='number'||!Number.isFinite(r.score)||!text(r.media_type,128))throw Error('result_invalid');if(r.page!==undefined&&(!Number.isSafeInteger(r.page)||r.page<0)||r.page_count!==undefined&&(!Number.isSafeInteger(r.page_count)||r.page_count<1||r.page!==undefined&&r.page>r.page_count)||((r.page!==undefined||r.page_count!==undefined)&&r.media_type!=='application/pdf')||r.media_type==='application/pdf'&&(!Number.isSafeInteger(r.page_count)||r.page_count<1))throw Error('page_invalid');return r as Result});return {total:v.total,results}}
 async evidence(r:Result,page:number|undefined,signal?:AbortSignal):Promise<Evidence>{const p=new URLSearchParams();if(page!==undefined)p.set('page',String(page));const v=await this.get(`/api/v1/documents/${encodeURIComponent(r.id)}${p.size?'?'+p:''}`,2<<20,signal);if(!id(v?.id)||v.id!==r.id||v.source_id!==r.source_id||!text(v.title,4096)||!text(v.path,2048)||v.path!==r.path||!text(v.uri,8192)||!text(v.source_name,512)||!text(v.media_type,128)||v.media_type!==r.media_type||!text(v.content_hash,128)||!text(v.modified_at,80)||!Number.isFinite(Date.parse(v.modified_at))||!text(v.text,1<<20)||typeof v.truncated!=='boolean')throw Error('evidence_invalid');if(page!==undefined&&v.page!==page&&!(page===0&&v.page===undefined&&v.media_type==='application/pdf'))throw Error('evidence_page_mismatch');if(page===undefined&&v.page!==undefined)throw Error('evidence_page_mismatch');if(v.page_count!==undefined&&(!Number.isSafeInteger(v.page_count)||v.page_count<1||v.page!==undefined&&v.page>v.page_count))throw Error('evidence_page_invalid');if(page===0&&(v.media_type!=='application/pdf'||!Number.isSafeInteger(v.page_count)||v.page_count<1))throw Error('evidence_page_invalid');if(page===0&&v.page===undefined)v.page=0;return v}
}
